version: '3.8'

services:
  planner:
    build:
      context: ./planner
      dockerfile: Dockerfile_planner
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile_worker
    ports:
      - "8081:8080"

    depends_on:
      - planner
