version: '3.8'

services:
  planner:
    build:
      context: ./planner
      dockerfile: Dockerfile_planner
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile_worker
 #   ports:
 #     - "8080:8080"
    networks:
      - mynetwork
    deploy:
      replicas: 10 

  worker1:
    build:
      context: ./worker
      dockerfile: Dockerfile_worker
    environment:
      - PORT=8070
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge